$ = jQuery = require('jquery');
angular = require('angular');
require('angular-cookies');
require('angular-resource');
require('angular-xeditable');
require('angular-ui-bootstrap');
require('angular-ui-router');
require('bootstrap');
moment = require('moment');
sprintf = require('sprintf');
toastr = require('toastr');
_ = require('underscore');
