"""Initial tables

Revision ID: 38a04263f254
Revises: 
Create Date: 2015-08-18 18:43:26.928836

"""

# revision identifiers, used by Alembic.
revision = '38a04263f254'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=225), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test-suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('test-events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('test_suite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_suite'], ['test-suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('test_suite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_suite'], ['test-suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test-sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('server', sa.String(length=225), nullable=False),
    sa.Column('browser', sa.String(length=225), nullable=False),
    sa.Column('tester', sa.String(length=225), nullable=False),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test-steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('action', sa.String(length=225), nullable=False),
    sa.Column('expected_result', sa.String(length=225), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test-event-results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_event', sa.Integer(), nullable=True),
    sa.Column('test_session', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_event'], ['test-events.id'], ),
    sa.ForeignKeyConstraint(['test_session'], ['test-sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test-results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('test_step', sa.Integer(), nullable=True),
    sa.Column('actual_result', sa.String(length=225), nullable=False),
    sa.Column('comments', sa.String(length=225), nullable=False),
    sa.Column('test_session', sa.Integer(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['test_session'], ['test-sessions.id'], ),
    sa.ForeignKeyConstraint(['test_step'], ['test-steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test-results')
    op.drop_table('test-event-results')
    op.drop_table('test-steps')
    op.drop_table('test-sessions')
    op.drop_table('tests')
    op.drop_table('test-events')
    op.drop_table('users_roles')
    op.drop_table('test-suites')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('projects')
    ### end Alembic commands ###
