"""default data and new tables

Revision ID: 3ee5b63b13b4
Revises: 38a04263f254
Create Date: 2015-09-11 14:51:02.645780

"""

# revision identifiers, used by Alembic.
revision = '3ee5b63b13b4'
down_revision = '38a04263f254'
branch_labels = None
depends_on = None

from alembic import op
from app.users.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('browsers')
    ### end Alembic commands ###
